language: go

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      go: "1.12"
    - os: osx
      go: tip
  allow_failures:
    - go: tip

go:
  - "1.12"
  - "1.13"
  - "1.14"
  - tip

script:
  - make
